name: "New Blog Post"
description: "Publish a new blog post by filling this form."
title: "[Blog] Your post title"
labels: ["blog", "publish"]
body:
  - type: input
    id: date
    attributes:
      label: Date
      description: "Use YYYY-MM-DD (ISO)."
      placeholder: "2025-02-28"
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Author
      placeholder: "Your name"
    validations:
      required: true
  - type: input
    id: category
    attributes:
      label: Category
      placeholder: "Inspiration, Tech, etc."
  - type: input
    id: tags
    attributes:
      label: Tags
      description: "Comma-separated (e.g., tech, teams)"
      placeholder: "tech, teams"
  - type: input
    id: image_url
    attributes:
      label: Image URL (optional)
      placeholder: "https://... or assets/img/..."
  - type: input
    id: image_alt
    attributes:
      label: Image Alt Text
      placeholder: "Describe the image"
  - type: textarea
    id: excerpt
    attributes:
      label: Excerpt (1–2 sentences)
      placeholder: "Short summary shown on the card"
  - type: textarea
    id: body
    attributes:
      label: Main Body
      description: "Write your post. Basic paragraphs supported; blank line = new paragraph."
      placeholder: "Your post content..."
    validations:
      required: true

